version: '1'

services:

# docker run --rm -d --name=forwarder-container2000 --network=host alpine/socat TCP-LISTEN:2000,fork TCP:$IP:2000
  forwarder-2000:
    image: alpine/socat
    command: TCP-LISTEN:2000,fork TCP:host.docker.internal:2000
    container_name: forwarder-container2000
    network_mode: host

# docker run --rm -d --name=forwarder-container1234 --network=host alpine/socat TCP-LISTEN:1234,fork TCP:$IP:1234
  forwarder-1234:
    image: alpine/socat
    command: TCP-LISTEN:1234,fork TCP:host.docker.internal:1234
    container_name: forwarder-container1234
    network_mode: host



